nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173'] #URL du FRONT
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Authorization']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': ~  # n’applique les règles qu’aux routes qui commencent par /api
